---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        custom: test-app
    spec:
      containers:
      - image: idwarlock/gb-hello:v1
        name: gb-hello
        ports:
        - containerPort: 80
